--- #YAML:1.0
name:               Cindy-Apache2
version:            0.05
abstract:           use unmodified XML or HTML documents as templates.
author:
    - JZOBEL (jz-2009@heute-morgen.de)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cindy:      0.11
    mod_perl2:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
