--- #YAML:1.0
name:                Cindy-Apache2
version:             0.01
abstract:            use unmodified XML or HTML documents as templates.
license:             ~
author:              
    - JZOBEL (jz-2009@heute-morgen.de)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache2::Request:              0
    Cindy:                         0.07
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
